-- ADR-0141 — la venta es una TRANSACCIÓN, no un hecho de sala.
--
-- `sales_sale.table_id` era el último sitio donde `sales` hablaba el idioma "mesa" sin depender de
-- `tables`: una tienda de alimentación no tiene mesas y vende igual. La asociación viva la OWNea
-- `tables` (`tables_session.order_id` → el pedido), y del pedido cuelgan sus ventas; quien quiera
-- saber en qué mesa se sirvió algo lo pregunta por ahí, no leyendo una columna de `sales`.
--
-- ⚠ DESTRUCTIVA: las ventas ya cerradas pierden ese dato (no hay a dónde moverlo — las sesiones de
-- mesa de entonces no guardaban `order_id`). Se acepta porque el producto está PRE-LANZAMIENTO: no
-- hay clientes de pago, y el dato solo alimentaba la comanda de cocina, que ahora nace del pedido.
-- Requiere SQLite 3.35+ (2021) — el runtime embebe una muy posterior.
ALTER TABLE sales_sale DROP COLUMN table_id;
